### ISSUE TITLE
easyDNS - Not vulnerable

### ISSUE THREAD

**Issue by markjr** [indianajson/can-i-take-over-dns#37]
### <code>Nameserver</code>

dns1.easydns.com
dns2.easydns.net
dns3.easydns.org
dns4.easydns.info

rush.easydns.com
nirvana.easydns.net
motorhead.easydns.org

dns1.easydnssec.com
dns2.easydnssec.net
dns3.easydnssec.org
dns4.easydnssec.info

### <code>Explanation</code>

easyDNS stopped allowing a domain to be added to the system that is a lame delegation without it being verified through adding a hostname to the nameserver delegation via the domain registrar.

**Comment by indianajson** [comment]
Integrated this information into the main issue for EasyDNS (#9). Thank you again!
